{
  "cliBin":"jcli",
  "daedalusBin":"daedalus-frontend",
  "frontendOnlyMode":true,
  "launcherLogsPrefix":"${XDG_DATA_HOME}/Daedalus/itn_rewards_v1/Logs/",
  "logsPrefix":"${XDG_DATA_HOME}/Daedalus/itn_rewards_v1/Logs",
  "nodeArgs":[],
  "nodeBin":"jormungandr",
  "nodeImplementation":"jormungandr",
  "nodeLogConfig":null,
  "nodeLogPath":null,
  "nodeTimeoutSec":60,
  "stateDir":"${XDG_DATA_HOME}/Daedalus/itn_rewards_v1",
  "tlsPath":null,
  "updateArchive":"/bar",
  "updateWindowsRunner":"",
  "updaterArgs":[],
  "updaterPath":"/foo",
  "walletArgs":["launch","--genesis-block-hash","8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676","--state-dir","${XDG_DATA_HOME}/Daedalus/itn_rewards_v1","--sync-tolerance","600s","--random-port","--","--config","/nix/store/xcdblmkd64382c7n4laq9wqzrdx9910h-jormungandr-config-itn_rewards_v1.yaml"],
  "walletBin":"cardano-wallet-jormungandr",
  "walletLogging":true,
  "workingDir":"${XDG_DATA_HOME}/Daedalus/itn_rewards_v1",
  "x509ToolPath":null
}
